name: Deploy Docs

on: push

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up V
        uses: vlang/setup-v@v1.1
        with:
          check-latest: true

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Checkout Site Repository
        uses: actions/checkout@v3
        with:
          repository: RGBCube/rgbcube.github.io
          path: site

      - name: Generate Docs
        run: |
          mv ./src ./revolt.v # For the docs header
          cp ./README.md ./revolt.v/ # For the README to be included in the docs.
          v doc -readme -f html -o ./ -m ./revolt.v

          rm -rf ./site/docs/revolt || true
          mkdir -p ./site/docs/revolt
          cp -r ./_docs/* ./site/docs/revolt/

      - name: Add Private Key To SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.RGBCUBE_GITHUB_IO_PRIVATE_KEY }}

      - name: Push Docs To GitHub
        continue-on-error: true
        run: |
          cd site

          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"

          git add ./
          git commit -m "Deploy revolt.v docs"
          git push git@github.com:RGBCube/rgbcube.github.io master
